string label            # Object label
float64 probability     # Confidence value in recognition
uint16 centroid_x       # X pixel value of the centroid of the bounding box
uint16 centroid_y       # Y pixel value of the centroid of the bounding box
uint16 left_bot_x       # X pixel value of bottom-left corner of bounding box
uint16 left_bot_y       # Y pixel value of bottom-left corner of bounding box
uint16 right_top_x      # X pixel value of top-right corner of bounding box
uint16 right_top_y      # Y pixel value of top-right corner of bounding box
